# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "swift" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      
  # Default Cooldown (90 days)   
  - package-ecosystem: "swift"
    open-pull-requests-limit: 16
    directory: "/cooldown_default"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 90

  # Semver Major Cooldown (60 days)
  - package-ecosystem: "swift"
    open-pull-requests-limit: 16
    directory: "/cooldown_major"
    schedule:
      interval: "daily"
    cooldown:
      semver-major-days: 60

   # Semver Minor Cooldown (60 days)
  - package-ecosystem: "swift"
    open-pull-requests-limit: 14
    directory: "/cooldown_minor"
    schedule:
      interval: "daily"
    cooldown:
      semver-minor-days: 60

  # Semver Patch Cooldown (60 days)
  - package-ecosystem: "swift"
    open-pull-requests-limit: 14
    directory: "/cooldown_patch"
    schedule:
      interval: "daily"
    cooldown:
      semver-patch-days: 60


  # Cooldown with Mixed Inclusion/Exclusion
  - package-ecosystem: "swift"
    open-pull-requests-limit: 14
    directory: "/cooldown_mixed"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 60
      include:
        - "phpunit/phpunit"
        - "mockery/mockery"
        - "squizlabs/php_codesniffer"
      exclude:
        - "friendsofphp/php-cs-fixer"
        - "fakerphp/faker"
